### PR TITLE
143 account for api implementation of actual concepts

### PR DESCRIPTION
**Pull request by fmatthies**
finished as far as accounting for concepts is concerned

### CODE REVIEW

**Comment by ChristophB** [comment]
It says that the dependency `top-document-query` could not be downloaded but all tests are passing.
See: https://github.com/Onto-Med/top-backend/pull/150/checks#step:4:16

Is this dependency currently used? If so, the following server entry must be added to `.mvn-ci.xml`:

```xml
<server>
    <id>top-document-query</id>
    <username>${env.GH_MAVEN_PKG_USER}</username>
    <password>${env.GH_MAVEN_PKG_AUTH_TOKEN}</password>
</server>
```

**Comment by ChristophB** [comment]
What is `care.smith.top.backend.configuration.nlp.ElasticsearchConfigBean` used for? Do we still need it?

Also: There is a dependency to `co.elastic.clients:elasticsearch-java`. Should the scope of this dependency be set to `test`?

**Comment by ChristophB** [comment]
> It says that the dependency `top-document-query` could not be downloaded but all tests are passing. See: https://github.com/Onto-Med/top-backend/pull/150/checks#step:4:16
> 
> Is this dependency currently used? If so, the following server entry must be added to `.mvn-ci.xml`:
> 
> ```
> <server>
>     <id>top-document-query</id>
>     <username>${env.GH_MAVEN_PKG_USER}</username>
>     <password>${env.GH_MAVEN_PKG_AUTH_TOKEN}</password>
> </server>
> ```

Stragely, the dependency is correctly downloaded. Is it included in one of the other dependencies?

**Review by ChristophB — APPROVED** [review]
Approving code changes. Please check my other comments.

**Comment by fmatthies** [comment]
> It says that the dependency `top-document-query` could not be downloaded but all tests are passing. See: https://github.com/Onto-Med/top-backend/pull/150/checks#step:4:16
> 
> Is this dependency currently used? If so, the following server entry must be added to `.mvn-ci.xml`:
> 
> ```
> <server>
>     <id>top-document-query</id>
>     <username>${env.GH_MAVEN_PKG_USER}</username>
>     <password>${env.GH_MAVEN_PKG_AUTH_TOKEN}</password>
> </server>
> ```

Yes, it's used and I read it as the `top-api (v0.9.0-SNAPSHOT)` dependency could not be downloaded. I added the `.mvn-ci.xml` nonetheless.

**Comment by fmatthies** [comment]
> > It says that the dependency `top-document-query` could not be downloaded but all tests are passing. See: https://github.com/Onto-Med/top-backend/pull/150/checks#step:4:16
> > Is this dependency currently used? If so, the following server entry must be added to `.mvn-ci.xml`:
> > ```
> > <server>
> >     <id>top-document-query</id>
> >     <username>${env.GH_MAVEN_PKG_USER}</username>
> >     <password>${env.GH_MAVEN_PKG_AUTH_TOKEN}</password>
> > </server>
> > ```
> 
> Stragely, the dependency is correctly downloaded. Is it included in one of the other dependencies?

It is not contained somewhere else. See above comment.
But there should be a `top-api-0.9.0-SNAPSHOT`, shouldn't there?

**Comment by ChristophB** [comment]
> > > It says that the dependency `top-document-query` could not be downloaded but all tests are passing. See: https://github.com/Onto-Med/top-backend/pull/150/checks#step:4:16
> > > Is this dependency currently used? If so, the following server entry must be added to `.mvn-ci.xml`:
> > > ```
> > > <server>
> > >     <id>top-document-query</id>
> > >     <username>${env.GH_MAVEN_PKG_USER}</username>
> > >     <password>${env.GH_MAVEN_PKG_AUTH_TOKEN}</password>
> > > </server>
> > > ```
> > 
> > 
> > Stragely, the dependency is correctly downloaded. Is it included in one of the other dependencies?
> 
> It is not contained somewhere else. See above comment. But there should be a `top-api-0.9.0-SNAPSHOT`, shouldn't there?

Seems like, Maven tries to download `top-api` from the `top-document-query` GitHub package too, because it is included there as a dependency. It says "status: 401 Unauthorized", if credentials are not provided for that mirror. Don't know why `top-document-query` is downloaded nontheless.

**Comment by fmatthies** [comment]
> What is `care.smith.top.backend.configuration.nlp.ElasticsearchConfigBean` used for? Do we still need it?
> 
Yes, it's used for being able to configure the index name via the application.yml. 
 
> Also: There is a dependency to `co.elastic.clients:elasticsearch-java`. Should the scope of this dependency be set to `test`?
>
Yes, you're right.

**Comment by fmatthies** [comment]
> > > > It says that the dependency `top-document-query` could not be downloaded but all tests are passing. See: https://github.com/Onto-Med/top-backend/pull/150/checks#step:4:16
> > > > Is this dependency currently used? If so, the following server entry must be added to `.mvn-ci.xml`:
> > > > ```
> > > > <server>
> > > >     <id>top-document-query</id>
> > > >     <username>${env.GH_MAVEN_PKG_USER}</username>
> > > >     <password>${env.GH_MAVEN_PKG_AUTH_TOKEN}</password>
> > > > </server>
> > > > ```
> > > 
> > > 
> > > Stragely, the dependency is correctly downloaded. Is it included in one of the other dependencies?
> > 
> > 
> > It is not contained somewhere else. See above comment. But there should be a `top-api-0.9.0-SNAPSHOT`, shouldn't there?
> 
> Seems like, Maven tries to download `top-api` from the `top-document-query` GitHub package too, because it is included there as a dependency. It says "status: 401 Unauthorized", if credentials are not provided for that mirror. Don't know why `top-document-query` is downloaded nontheless.

Weird. Also because I set the `top-api` dependency within the `top-document-query` pom to 'exclude'.

**Comment by ChristophB** [comment]
> > 
> > 
> > Seems like, Maven tries to download `top-api` from the `top-document-query` GitHub package too, because it is included there as a dependency. It says "status: 401 Unauthorized", if credentials are not provided for that mirror. Don't know why `top-document-query` is downloaded nontheless.
> 
> Weird. Also because I set the `top-api` dependency within the `top-document-query` pom to 'exclude'.

Could be the case that using "*-SNAPSHOT" forces Maven to scan all mirrors for the latest snapshot of that package.

**Pull request merged**
