### PR TITLE
191 concept graphs use documents from different source than upload

### PR DESCRIPTION
**Pull request by fmatthies**
there are now methods to start the concept graph creation using an external document server and not relying on txt document upload

### CODE REVIEW

**Comment by fmatthies** [comment]
I did indeed wonder why there were only `pom` changes when I was rebasing. I didn't intentionally omit commits... don't know why this happened

**Comment by fmatthies** [comment]
This is weird (wrote about it in the last commit message). Need to look into it.

**Comment by fmatthies** [comment]
And it just happens during tests because locally my backend runs with the new changes

**Comment by ChristophB** [comment]
> And it just happens during tests because locally my backend runs with the new changes

It looks to me like you are modifying the application context in `TopBackendApplication::main', which is not called when the tests are run.

**Comment by fmatthies** [comment]
Yeah, you're right. But it never happened before (maybe I have defaults in the value annotion everywhere else); that threw me off.

**Comment by fmatthies** [comment]
It's so frustrating: locally the test are passing. I will look into it some more. Hopefully you aren't spammed with the notifications about the failing tests?

**Comment by fmatthies** [comment]
So the real reason for all the failures (I fixed them now except for the `getDataSources` Test in `QueryApiDelegateImplTest`) seems to be that the `test/resources` are not used (or old? ones). So the `getDataSources` Test just finds 2 (and not my `nlp/Test_Data_Source_3.yml`).

**Comment by fmatthies** [comment]
Not default ones but the ones declared in the adapter. The remaining error resulted from the test documents being indexed not in `test_documents` but in `documents`. Hopefully my commit fixes that.
Thanks for your help! Don't know how long it would have taken me to arrive at that solution 🤔

**Comment by fmatthies** [comment]
> Some commits are not properly rebased from `master` - e.g. [f124dff](https://github.com/Onto-Med/top-backend/pull/196/commits/f124dffb9b6d1821f743c9fd80b08be74ed4b306) (has it been cherry-picked?)
> 
> When the tests are passing, I'll drop the affected commits and do a rebase afterwards.

@ChristophB now all tests are passing; finally.

**Comment by ChristophB** [comment]
Cleaned up the branch and rebased onto master.

**Review by ChristophB — COMMENTED** [review]
Could you please check that `README.md` contains up-to-date information about the concept graph integration?

**Comment by ChristophB** [comment]
I'll do the merge as there is another unwanted commit [005409b](https://github.com/Onto-Med/top-backend/pull/196/commits/005409b7fed11f468da4b44f524d232d1c764b68).

**Comment by ChristophB** [comment]
@fmatthies What is the purpose of this commit? [abb59ae](https://github.com/Onto-Med/top-backend/pull/196/commits/abb59ae4f87b47154622f45a97add7801d9745df) It is from January 18 and introduced an unused method.

**Pull request merged**
